# Generated by Django 3.1.13 on 2021-11-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Margin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "west",
                    models.DecimalField(decimal_places=6, default=0.2, max_digits=9),
                ),
                (
                    "east",
                    models.DecimalField(decimal_places=6, default=0.2, max_digits=9),
                ),
                (
                    "north",
                    models.DecimalField(decimal_places=6, default=0.2, max_digits=8),
                ),
                (
                    "south",
                    models.DecimalField(decimal_places=6, default=0.2, max_digits=8),
                ),
            ],
            options={
                "verbose_name": "Margin",
                "ordering": ["west", "east", "north", "south"],
            },
        ),
        migrations.AddConstraint(
            model_name="margin",
            constraint=models.UniqueConstraint(
                fields=("west", "east", "north", "south"), name="unique"
            ),
        ),
    ]
