# Generated by Django 3.1.13 on 2022-03-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("margins", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="margin",
            name="unique",
        ),
        migrations.AddConstraint(
            model_name="margin",
            constraint=models.UniqueConstraint(
                fields=("west", "east", "north", "south"), name="unique_margin"
            ),
        ),
    ]
