# Generated by Django 3.1.13 on 2022-03-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface_meteograms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smpoints',
            name='name',
            field=models.CharField(choices=[('HERE', 'Point location'), ('ALL', 'All points'), ('LAND', 'Land points'), ('SEA', 'Sea points'), ('NEAR', 'Nearest point')], default='HERE', max_length=4),
        ),
    ]
