# Generated by Django 3.1.13 on 2021-11-15 13:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model_grids", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelgrid",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                dim=3, srid=4326
            ),
        ),
    ]
