# Generated by Django 3.1.13 on 2022-01-03 08:08

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('model_grids', '0002_auto_20211115_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='Variable name')),
            ],
            options={
                'ordering': ['model_grid', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='modelgrid',
            options={'ordering': ['name', 'date_valid_start']},
        ),
        migrations.AddField(
            model_name='modelgrid',
            name='date_valid_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='modelgrid',
            name='date_valid_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='modelgrid',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True, verbose_name='ModelGrid name'),
        ),
        migrations.AddConstraint(
            model_name='modelgrid',
            constraint=models.UniqueConstraint(fields=('name', 'date_valid_start'), name='unique_model_grid'),
        ),
        migrations.AddField(
            model_name='variable',
            name='model_grid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_grids.modelgrid'),
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.UniqueConstraint(fields=('name', 'model_grid'), name='unique_variable'),
        ),
    ]
