# Generated by Django 3.1.13 on 2022-05-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vertical_meteograms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verticalmeteogram",
            name="img_path",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="verticalmeteogram",
            name="subtext",
            field=models.TextField(blank=True, null=True),
        ),
    ]
