# Generated by Django 3.1.13 on 2022-03-01 10:08
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [CITextExtension()]
