# Generated by Django 3.1.13 on 2022-03-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
