# Generated by Django 3.1.13 on 2022-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0001_initial'),
        ('stations', '0003_station_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='alt_lower',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lower altitude of the release', max_digits=6),
        ),
        migrations.AddField(
            model_name='station',
            name='alt_unit',
            field=models.IntegerField(choices=[(1, 'm (ab. ground)'), (2, 'm (ab. sea level)'), (3, 'hPa')], default=1, help_text='Altitude unit'),
        ),
        migrations.AddField(
            model_name='station',
            name='alt_upper',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Upper altitude of the release', max_digits=6),
        ),
        migrations.AddField(
            model_name='station',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Ending date of the release', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='numb_part',
            field=models.PositiveIntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='station',
            name='number_grid',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='station',
            name='plots',
            field=models.ManyToManyField(blank=True, related_name='stations', to='plots.StationsPlot'),
        ),
        migrations.AddField(
            model_name='station',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Starting date of the release', null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='uses_flexpart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='station',
            name='xmass',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
