# Generated by Django 3.1.13 on 2022-08-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20220810_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='alt_unit',
            field=models.IntegerField(choices=[(1, 'm (a.g.l)'), (2, 'm (a.s.l)'), (3, 'hPa')], default=1, help_text='Altitude unit'),
        ),
    ]
