# Generated by Django 3.1.13 on 2022-08-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_auto_20220822_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='alt_lower',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
