# Generated by Django 3.1.13 on 2021-09-28 09:42
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = []

    operations = [CITextExtension()]
